language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install pytest
- pip install pytest-cov
- pip install codecov
install:
- pip install .
script:
- export NUMBA_DISABLE_JIT="1" && pytest -m "not notebook_tests" --junitxml=pytest-report.xml 
  --cov-config=.coveragerc --cov-report xml --cov
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  user: __token__
  password: $pypi_token
  on:
    tags: true
  skip_cleanup: true
