language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install nose2
  - pip install codecov
install:
  - pip install .
script: 
  - export NUMBA_DISABLE_JIT="1" && nose2 --plugin nose2.plugins.junitxml --with-coverage --coverage pandora --coverage-report xml -X
after_success:
  - codecov #coverage