# pylint: skip-file
def cbca_step_1(input): ...
def cbca_step_2(step1, cross_left, cross_right, range_col, range_col_right): ...
def cbca_step_3(step2): ...
def cbca_step_4(step3, sum2, cross_left, cross_right, range_col, range_col_right): ...
def cross_support(image, len_arms, intensity): ...
