# pylint: skip-file
def compute_ambiguity(cv, etas, nbr_etas, grids, disparity_range, type_measure_min): ...
def compute_ambiguity_and_sampled_ambiguity(cv, etas, nbr_etas, grids, disparity_range): ...
def compute_interval_bounds(cv, disp_interval, possibility_threshold, type_factor): ...
def compute_risk_and_sampled_risk(cv, sampled_ambiguity, etas, nbr_etas, grids, disparity_range, sample_risk): ...
